import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/flea.png'
import bgImage from '../../assets/services/bg/ticks_fleas.png'

export default function FleaPestControl() {
  return <ServiceDetailPage
    meta={{ title: 'Flea & Tick Control in Bangalore | A to Z Pest Solutions', desc: 'Professional flea and tick pest control in Bangalore. Safe for pets and children. Eliminates all life stages including eggs and larvae. Call 9845559710 for FREE inspection.', canonical: 'https://pestcontrolbengaluru.in/ticks-fleas-treatment' }}
    image={imgPest} bgImage={bgImage} title="Ticks & Fleas Treatment" tagline="Fleas reproduce 50x faster than common pests. Our 3-stage lifecycle treatment eliminates them completely — including the invisible eggs."
    intro="Ctenocephalides felis (cat flea) and Ctenocephalides canis (dog flea) are the two most prevalent flea species found in Bangalore households with pets. Despite their names, both species readily infest and bite humans. A single female flea lays up to 50 eggs per day — meaning an infestation can grow from 10 fleas to over 250,000 in just 30 days. Crucially, only 5% of a flea infestation consists of adult fleas — the remaining 95% are eggs, larvae, and pupae hidden deep in carpets, upholstery, and floor cracks, invisible to the naked eye. For ticks, Rhipicephalus sanguineus (Brown Dog Tick) is the primary species in Bangalore, capable of transmitting Rocky Mountain Spotted Fever, Babesiosis, and Ehrlichiosis. A to Z Pest Solutions employs a clinically validated 3-stage Integrated Lifecycle Treatment that simultaneously targets all four flea life stages and all tick life stages for complete elimination."
    signs={['Small, red, intensely itchy bites in clusters — typically on ankles, lower legs, and feet','Pets (dogs or cats) scratching excessively, biting at their skin, or rolling on the floor in distress','Flea dirt — tiny black specks (digested blood) — visible in pet bedding, carpets, and on pet fur (turns red when wet)','Seeing tiny, fast-moving dark insects (1–2mm) jumping across light-colored flooring or bedding','Pets developing skin hotspots, hair loss, or Flea Allergy Dermatitis (FAD) — caused by an allergic reaction to flea saliva','White, rice-grain-sized tapeworm segments visible in pet feces — tapeworm transmission is a direct consequence of flea infestation','Unexplained pale gums in puppies or kittens (sign of anemia from heavy flea blood-feeding)','Tick visible on pet skin — particularly around ears, between toes, and under collar areas']}
    benefits={['Insect Growth Regulators (IGRs — Methoprene/Pyriproxyfen) halt egg and larval development for 6 months — preventing new adult fleas from emerging','Adulticide spray (Deltamethrin 2.5% SC) kills all adult fleas on contact and provides 45-day residual protection','Deep carpet and upholstery treatment targeting the 95% of infestation hidden in floor level environments','Pet-safe formulations — all insecticides used are at concentrations safe for dogs and cats once dried','Tick acaricide treatment eliminates all life stages including larvae (seed ticks), nymphs, and adults','Treatment covers entire property — floors, walls, furniture bases, pet resting areas, and garden perimeter','Free follow-up treatment at Day 21 (peak egg-hatch window) included in all packages','Guidance on pet veterinary treatments (topical spot-ons, oral flea preventatives) to complement professional treatment']}
    process={[
      { title: 'Pre-Treatment Preparation & Pet Veterinary Coordination', desc: 'We advise you to vacuum all carpets and upholstered furniture thoroughly (dispose of vacuum bag immediately), launder all pet bedding at 60°C+, and take pets to a veterinarian for professional grooming and topical flea/tick treatment. This removes surface adult fleas and ensures our treatment targets the deeper infestation without interference.' },
      { title: 'Detailed Infestation Mapping', desc: 'Our technician maps all flea and tick hotspots using a UV torch (flea eggs fluoresce) and a fine-tooth comb on carpet samples. Pet resting areas, sleeping spots, crawl spaces, garden entry points, and kennel areas are all assessed to determine infestation density and distribution.' },
      { title: 'Insect Growth Regulator (IGR) Application', desc: 'Methoprene or Pyriproxyfen IGR is applied to all floor surfaces, carpets, rugs, and upholstery. IGRs mimic juvenile flea hormones — preventing flea eggs and larvae from developing into biting adult fleas. This breaks the reproductive cycle and prevents re-infestation for 6 months.' },
      { title: 'Adulticide Treatment', desc: 'Deltamethrin 2.5% SC residual spray is applied to all floor surfaces, carpet edges, wall-floor junctions, underneath furniture, and pet resting areas. This kills all adult fleas and ticks on contact and provides 45-day residual protection against newly hatching adults.' },
      { title: 'Day-21 Follow-Up Treatment', desc: 'We return at Day 21 — timed precisely to the peak emergence window for flea pupae (which are impervious to insecticides). Any newly hatched adults are killed by the residual treatment or re-treated. This follow-up is scientifically essential and is included in all our flea treatment packages at no additional charge.' },
    ]}
    faqs={[
      { q: "Can fleas live on humans?", a: "Fleas cannot permanently live on humans — we have too little hair. However, Pulex irritans (human flea) can bite humans repeatedly. More commonly in Bangalore, cat and dog fleas bite humans frequently, causing severe itching, secondary skin infections, and in some cases, allergic reactions." },
      { q: "My pet has been treated by the vet, but I still have fleas. Why?", a: "Because 95% of a flea infestation lives in the environment (floors, carpets, furniture) — not on the pet. Veterinary treatment kills fleas on the animal, but eggs and larvae in carpets continue to hatch and reinfest your pet. Professional environmental treatment of your home is required alongside veterinary treatment." },
      { q: "How long does flea treatment take to work?", a: "Adult fleas die within 24–48 hours of treatment. However, flea pupae (cocoons) are impervious to all insecticides — they must hatch into adults before being killed. The full lifecycle treatment typically takes 3–6 weeks. This is why our Day-21 follow-up is essential." },
      { q: "Is the treatment safe for my dog, cat, or rabbit?", a: "Yes. We use formulations approved for use in pet-occupied homes. Pets should be kept away from treated areas for 4 hours while surfaces dry. Once dry, the treatment is completely safe. We do not treat aquariums directly — fish tanks should be covered during treatment." },
      { q: "Can fleas transmit diseases to humans?", a: "Yes. Fleas are vectors for Murine Typhus (Rickettsia typhi), Bubonic Plague (historically), Bartonellosis (Cat Scratch Disease), and are the primary transmission route for tapeworm (Dipylidium caninum) in both pets and children who accidentally ingest infected fleas." },
      { q: "What diseases do ticks transmit in Bangalore?", a: "In Karnataka, ticks are vectors for Kyasanur Forest Disease (KFD — a hemorrhagic fever found in districts bordering forest areas), Spotted Fever Rickettsiosis, Babesiosis (in dogs), and Ehrlichiosis. The Brown Dog Tick (Rhipicephalus sanguineus) is the primary domestic species in Bangalore." },
      { q: "How quickly can a flea infestation develop?", a: "A flea population can double in size every 2–3 weeks. A single undetected flea pair can produce 250,000+ offspring in 30 days. Early professional intervention is critical — infestations that are ignored for 2+ months are substantially more difficult and expensive to eliminate." },
      { q: "What is the cost of flea and tick treatment in Bangalore?", a: "Treatment costs ₹1,500–₹3,500 for a standard 2BHK apartment with pets. Homes with severe infestations or large outdoor areas may cost ₹4,000–₹7,000. The Day-21 follow-up visit is included in all packages." },
      { q: "Do I need to remove my carpets after flea treatment?", a: "No. You should not remove carpets — this disrupts the IGR treatment and exposes untreated sub-floor areas. Keep treated carpets in place for at least 6 months. Vacuuming can resume 48 hours after treatment (this actually stimulates pupal hatching, exposing more fleas to the residual treatment)." },
      { q: "How can I prevent flea and tick infestations?", a: "Use veterinarian-recommended monthly topical spot-on treatments (Frontline Plus, Revolution) or oral preventatives (NexGard, Bravecto) on all pets year-round. Check pets for ticks after outdoor walks. Regularly wash pet bedding at 60°C. Vacuum carpets weekly. Our quarterly pet-home protection plans provide year-round professional coverage." },
    ]}
  />
}
