import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/honey_bee.png'
import bgImage from '../../assets/services/bg/honeybee.png'

export default function HoneyBeeTreatment() {
  return <ServiceDetailPage
    meta={{ title: 'Honey Bee Removal in Bangalore | A to Z Pest Solutions', desc: 'Safe, humane honey bee hive removal and relocation in Bangalore. Eco-conscious, harm-free bee control. Expert team. Call 9845559710 for emergency bee removal.', canonical: 'https://pestcontrolbengaluru.in/honey-bee-treatment' }}
    image={imgPest} bgImage={bgImage} title="Honey Bee Treatment" tagline="Honey bees are irreplaceable pollinators. We remove hives safely — protecting both your family and the bees."
    intro="The Indian honey bee (Apis cerana indica) and Rock bee (Apis dorsata) are the most common bee species forming hives in Bangalore's residential areas. A single hive can house 10,000–80,000 bees and produce 30–40 kg of honey. While honey bees are critical pollinators responsible for one-third of our food supply, hives on residential walls, rooftops, trees, or water tanks pose serious stinging risks — particularly for individuals with bee venom allergies (anaphylaxis), which requires immediate medical attention. A to Z Pest Solutions specializes in ethical, bee-safe hive removal and colony relocation, working with local apiaries to ensure displaced colonies are safely rehomed. Where relocation is not possible, we use targeted bee-dispersal treatments that encourage the swarm to vacate without fatality."
    signs={['A visible hive — from golf-ball size to football size or larger — on exterior walls, trees, rooftops, or in wall cavities','Significantly increased bee activity around one specific area of the property','Honey or beeswax dripping or staining through walls or ceilings (indicates a hive inside the wall cavity)','Bees entering and exiting through a small crack or gap in your wall, soffit, or roof','Buzzing sounds emanating from inside walls or above ceilings','A fresh bee swarm clustered on a tree branch, fence, or exterior surface (swarms are temporary but will form a permanent hive within 24–72 hours)','Bees showing aggressive behavior near a specific building area','Dead bees accumulating on windowsills or near light fixtures inside the building']}
    benefits={['Ethical, harm-minimizing approach — colony relocation preferred over extermination','Expert removal from any height — ground level to 60-foot rooftops','Specialist protective equipment for safe operations in high-infestation zones','Complete honeycomb and wax removal to prevent honey fermentation, wall damage, and secondary pest attraction','Entry point sealing to prevent future colony establishment in the same location','Emergency same-day response for active bee swarms','No lingering bee scent attractants post-treatment — reduces re-colonization risk','Safe for children, pets, and garden plants throughout the process']}
    process={[
      { title: 'Emergency Assessment & Safety Perimeter', desc: 'Our specialist arrives and establishes a safety perimeter, ensures all occupants are at a safe distance, and assesses the hive: species identification, size estimation, location (exposed vs. wall-cavity), and best removal strategy. Persons with known bee allergies are advised to remain indoors.' },
      { title: 'Protective Setup & Equipment Deployment', desc: 'Full beekeeper-grade PPE is donned (ventilated suit, gloves, veil). Removal equipment is prepared: bee vacuum (for live collection), wooden collection box for the colony, and long-reach tools for elevated hives. Smoke is used when necessary to calm the bees before approach.' },
      { title: 'Humane Hive Removal & Colony Collection', desc: 'The hive is systematically removed from the structure. Live bees are carefully collected using a professional bee vacuum into a sealed transport box. The queen bee is located and secured first — the colony follows her. For wall-cavity hives, a small access opening is made (with the owner\'s consent) to reach the internal comb.' },
      { title: 'Honeycomb & Wax Removal', desc: 'All honeycomb, wax, and honey residue is completely removed from the structure. Leaving honeycomb behind is a critical error — honey ferments, seeps through walls, attracts ants, wasps, and secondary bee colonies, and causes structural damage. Our team removes every fragment.' },
      { title: 'Colony Relocation & Site Sealing', desc: 'The collected colony is transported to a partnered local apiary or agricultural area where they continue their vital pollination work. All entry gaps are sealed with weather-resistant expanding foam and wire mesh. A perimeter spray of bee-deterrent (citronella-based) is applied to discourage future hive establishment at the same location.' },
    ]}
    faqs={[
      { q: "Are honey bees protected in India? Can you kill them?", a: "Honey bees are not officially listed as a protected species under India's Wildlife Protection Act 1972, but they are ecologically critical pollinators. A to Z Pest Solutions always prioritizes live removal and relocation over extermination. Extermination is only used as a last resort when the hive is inaccessible or relocation is impossible." },
      { q: "What should I do immediately if I discover a bee hive?", a: "Do not disturb the hive. Keep all family members, especially children and pets, away from the area. Do not spray water or aerosols at the hive — this triggers a defensive swarm. Close windows and doors near the hive. Call us immediately for an assessment." },
      { q: "How dangerous is a bee sting? When should I go to hospital?", a: "A single bee sting causes localized pain and swelling that subsides in 1–3 hours. Multiple stings (50+) can be medically serious for anyone. If a person is stung and develops hives, facial swelling, difficulty breathing, or dizziness, call emergency services immediately — these are signs of anaphylaxis." },
      { q: "Will the bees come back after removal?", a: "If the honeycomb and all wax residue is completely removed AND the entry points are properly sealed, bees will not return to the same location. The bee scent attractant in leftover wax is the primary cause of re-colonization — which is why complete comb removal is essential." },
      { q: "How long does bee hive removal take?", a: "Accessible, exposed hives take 1–3 hours depending on size. Hives inside wall cavities may require 3–6 hours. Emergency swarm removal (temporary clusters) can be completed in under 60 minutes." },
      { q: "Is bee removal dangerous for my property?", a: "For wall-cavity hives, we make the minimum access opening necessary and fully seal and restore it after removal. Our team photographs the area before and after. Any minor restoration work is included in the service quotation." },
      { q: "What is the cost of bee hive removal in Bangalore?", a: "Bee hive removal costs range from ₹1,500 for small, accessible hives to ₹8,000 for large wall-cavity hives requiring access opening and comb removal. Emergency same-day response carries an additional surcharge of ₹500–₹1,000." },
      { q: "Is smoke harmful to bees?", a: "No. Smoke triggers bees' evolutionary response to forest fires — they gorge on honey in preparation to flee, which makes them docile and less likely to sting. The smoke we use is cool, produced from natural materials (burlap, dried wood) and causes no lasting harm to the bees." },
      { q: "Can a bee swarm move on its own?", a: "Yes. A temporary swarm (bees clustered on a branch without building a comb) will naturally relocate within 24–72 hours once scout bees find a suitable permanent location. However, if they find a suitable cavity in your building during this window, they will establish a permanent hive. We recommend removal within 12 hours of discovering a swarm." },
      { q: "Do you remove wasp nests and hornet nests as well?", a: "Yes. We remove paper wasp nests (Polistes spp.), yellow jacket wasp hives, and Asian hornet nests using targeted treatment. Wasp and hornet removal is simpler than bee removal as ethical relocation considerations do not apply — insecticide injection into the nest is the standard treatment." },
    ]}
  />
}
