import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/post_construction.png'
import bgImage from '../../assets/services/bg/termite.png'

export default function PostConstructionTermite() {
  return <ServiceDetailPage
    meta={{ title: 'Post-Construction Termite Treatment in Bangalore | A to Z Pest Solutions', desc: 'Expert Drill-Fill-Seal post-construction anti-termite treatment in Bangalore. CIB-approved termiticides. 5-year warranty. Call 9845559710 for FREE inspection.', canonical: 'https://pestcontrolbengaluru.in/post-construction-termite-treatment' }}
    image={imgPest} bgImage={bgImage} title="Post-Construction Termite Treatment" tagline="Termites have already entered your home — but it's not too late. Our Drill-Fill-Seal method creates an impenetrable barrier in just one day."
    intro="Post-construction anti-termite treatment — universally known as the Drill-Fill-Seal (DFS) method — is the definitive solution for eliminating active termite infestations and preventing future attacks in existing, occupied buildings. Since the foundation soil is covered by flooring, walls, and structural elements, treatment must be delivered through precisely drilled access holes. A to Z Pest Solutions performs DFS treatment in strict compliance with BIS IS 6313 (Part 3), using CIB-registered termiticides (Bifenthrin 10% EC or Imidacloprid 30.5% SC) to eliminate Coptotermes gestroi, Odontotermes obesus, and Heterotermes indicola colonies — the three most destructive termite species in Bangalore. Our 5-year warranty-backed treatment is the same method used by the BMRDA, BBMP, and major Bangalore builders for their post-construction remediation."
    signs={['Mud shelter tubes (pencil-thick to thumb-thick) running up exterior and interior walls, plumbing pipes, or electrical conduits','Hollow, drum-like sound when you knock on wooden doors, frames, skirting boards, or furniture','Active termite workers — pale, white soft-bodied insects — visible inside broken mud tubes or damaged wood','Discarded termite wings (alates/swarmers) in clusters near windows, light sources, or door frames — typically after the first monsoon rain','Blistered, raised, or discolored patches on painted walls that feel damp or hollow underneath','Cracked plaster, small holes, or powdery cavities in masonry or grouting along wall-floor junctions','Severely damaged wooden furniture, books, or paper products stored on or near ground level','Damaged structural elements: door frames, window sills, or floor boards that are noticeably weakened']}
    benefits={['Targeted Drill-Fill-Seal method creates a continuous sub-floor chemical barrier in existing buildings','Bifenthrin 10% EC or Imidacloprid 30.5% SC — highest-efficacy CIB-registered termiticides','5-year warranty with free annual inspection visits during warranty period','Odorless, low-toxicity formulations — residents do not need to vacate','Color-matched cement sealing of drill holes — aesthetically invisible after treatment','Treatment of infested woodwork with boron-based preservative included','Same-day service available for urgent commercial and residential emergencies','BBMP-recognized certificate issued for property documentation and insurance']}
    process={[
      { title: 'Comprehensive Property Inspection & Mapping', desc: 'A certified technician performs a room-by-room inspection, mapping all active mud tubes, hollow-sounding wood, entry points, termite species present, and infestation severity on a detailed floor plan. This map guides precise drill placement for maximum chemical coverage.' },
      { title: 'Strategic Precision Drilling', desc: 'Holes of 12mm diameter are drilled at 300mm (12-inch) intervals at a 45° angle along the junction of all internal and external walls at floor level. Additional holes are drilled along skirting boards, around plumbing entry points, and at identified high-activity zones.' },
      { title: 'High-Pressure Termiticide Injection', desc: 'CIB-registered termiticide (Bifenthrin 10% EC at 5–7 L/m² or Imidacloprid 30.5% SC) is injected under pressure through each drilled hole until soil saturation is achieved. The pressurized injection ensures the chemical penetrates laterally and downward through the soil, creating a continuous horizontal barrier.' },
      { title: 'External Perimeter Trenching', desc: 'A 300mm deep × 150mm wide channel is cut along the exterior foundation and treated with termiticide at 7.5 L/running metre — creating the outer ring of the barrier system and preventing colony re-entry from surrounding soil.' },
      { title: 'Wood Treatment for Infested Timber', desc: 'All termite-damaged wooden elements (door frames, skirting boards, window frames) are injected with Boron-based wood preservative (Disodium Octaborate) at identified damage points — killing active foragers and preventing further wood consumption.' },
      { title: 'Drill Hole Sealing & Documentation', desc: 'All drill holes are sealed with white cement and color-matched masonry putty, making the treatment visually imperceptible. A detailed treatment report documenting chemicals used, application rates, and treatment coverage is issued alongside the official 5-year warranty certificate.' },
    ]}
    faqs={[
      { q: "How long does post-construction termite treatment take?", a: "A standard 2BHK (900–1,200 sqft) apartment takes 4–6 hours. Larger properties (3BHK villas, commercial spaces) typically require 6–10 hours. The drilling phase is the most time-consuming, but we complete treatment in a single day without requiring residents to vacate." },
      { q: "Will the drilling damage my marble or granite flooring?", a: "We drill only at the wall-floor junction (behind skirting boards) and along walls — not through open flooring. Holes are precisely 12mm in diameter and are sealed with cement matching the floor color. For premium marble installations, we use specialized diamond-tip bits and provide extra care during sealing to minimize visual impact." },
      { q: "Can you treat termites in individual rooms, or must the entire home be treated?", a: "For complete barrier integrity, IS 6313 requires treatment of the entire floor perimeter. Treating individual rooms creates gaps in the barrier that termites will simply route around. Partial treatment is significantly less effective and is not covered by our warranty. Full-property treatment is always recommended." },
      { q: "What is the cost of post-construction termite treatment in Bangalore?", a: "Costs range from ₹3,500–₹8,000 for a 1–2BHK apartment and ₹8,000–₹18,000 for a 3BHK villa, depending on total perimeter length, floor type, and infestation severity. We provide a detailed quotation after the free inspection." },
      { q: "Do I need to move furniture for the treatment?", a: "You need to clear a 12-inch strip along all walls to allow our team to drill and apply chemicals. Heavy furniture along walls should be temporarily moved. We advise you exactly what to prepare at the time of booking." },
      { q: "What is the warranty for post-construction termite treatment?", a: "We provide a 5-year warranty. If any termite activity is detected within this period, we re-treat the affected sections at zero cost. Annual free inspection visits are included within the warranty period to proactively monitor barrier integrity." },
      { q: "Is the termiticide safe for my pets and children?", a: "Yes. Bifenthrin and Imidacloprid are applied to the soil beneath the floor surface and are inaccessible to pets or children. Surface contact with walls is minimal. We recommend keeping pets and children away from the drilling area on treatment day. Normal activity can resume within 4 hours of treatment completion." },
      { q: "Can termites come back after Drill-Fill-Seal treatment?", a: "Within the 5-year warranty period, re-infestation is extremely rare when treatment is correctly applied with continuous barrier coverage. Gaps in drilling pattern (missed areas) or physical breaches of the soil (new plumbing, construction work) are the most common causes of post-treatment activity, all of which are covered by free re-treatment." },
    ]}
  />
}
