import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/pre_construction.png'
import bgImage from '../../assets/services/bg/termite.png'

export default function PreConstructionTermite() {
  return <ServiceDetailPage
    meta={{ title: 'Pre-Construction Termite Treatment in Bangalore | A to Z Pest Solutions', desc: 'BIS IS 6313-compliant pre-construction anti-termite soil treatment in Bangalore. 10-year warranty. CIB-approved chemicals. Call 9845559710 for a free site assessment.', canonical: 'https://pestcontrolbengaluru.in/pre-construction-termite-treatment' }}
    image={imgPest} bgImage={bgImage} title="Pre-Construction Termite Treatment" tagline="The most cost-effective termite protection is the one done before your building goes up — preventing ₹10 lakh+ in future repair costs."
    intro="Pre-construction anti-termite soil treatment is the first line of defense against subterranean termites and is mandated by the Bureau of Indian Standards BIS IS 6313 (Part 2) for all new construction in India. Applied during construction when the soil is fully exposed, this treatment creates an unbroken continuous chemical barrier beneath and around the entire structure — completely preventing subterranean termite (Coptotermes and Odontotermes spp.) colonies from entering the building from the ground. Unlike post-construction treatment which requires drilling through finished floors, pre-construction treatment achieves 100% barrier coverage at a fraction of the cost — making it the most economical and comprehensive termite protection available. A to Z Pest Solutions carries out pre-construction treatment using CIB-registered termiticides (Chlorpyrifos 20% EC or Bifenthrin 10% EC) strictly following IS 6313 Part 2 specifications, with a 10-year warranty certificate issued upon completion."
    signs={['Under-construction property on or near former agricultural or garden land (high termite soil activity)','Construction site adjacent to older buildings with known termite history','High organic matter, clay-rich, or damp soil conditions on the site — preferred termite habitat','Mud tubes or termite activity visible in soil during excavation or foundation work','Proximity to large trees, tree stumps, or wood debris that harbors termite colonies']}
    benefits={['100% continuous chemical barrier — impossible to achieve with post-construction methods','Strictly IS 6313 (Part 2) compliant — satisfies government, bank, and insurance requirements','10-year warranty on treatment — the longest available termite protection guarantee','Prevents future damage to RCC foundations, masonry, wooden flooring, and all internal woodwork','CIB-registered Chlorpyrifos and Bifenthrin termiticides — proven effective over decades','Treatment certificate issued for BBMP approvals, home loans, and property valuation','Significantly lower cost per square foot than equivalent post-construction treatment','No disruption to residents — treatment is completed before occupancy']}
    process={[
      { title: 'Pre-Construction Site Assessment', desc: 'Our specialist visits the construction site, assesses soil composition, checks for existing termite activity in the soil, identifies high-risk zones (near tree stumps, old structures), and designs the treatment schedule to align with construction milestones.' },
      { title: 'Foundation Trench Treatment (Stage 1)', desc: 'When foundation trenches are dug and before concrete is poured, Chlorpyrifos 20% EC solution is applied at 5 L/m² to the bottom and sides of all trenches. This creates the first treatment layer — directly at the termite access zone below foundation level.' },
      { title: 'Backfill Soil Treatment (Stage 2)', desc: 'As excavated earth is used to backfill around foundation columns and plinth walls, each layer is treated with termiticide at 7.5 L/m² before compaction. This creates a continuous treated-soil envelope around all sub-structure elements.' },
      { title: 'Plinth Level Treatment (Stage 3)', desc: 'Before the stone bed and DPC (Damp Proof Course) is laid, the consolidated earth within the plinth walls is treated at 5 L/m². This stage treats the most critical zone — the area directly beneath the ground floor.' },
      { title: 'Wall-Floor Junction Treatment (Stage 4)', desc: 'Before floor screed is laid, a concentrated application (7.5 L/m running metre) is made along both sides of all internal and external wall-floor junctions — the most common termite entry point in any building.' },
      { title: 'External Perimeter Treatment (Stage 5)', desc: 'After construction is complete, a final perimeter treatment is applied to a 300mm wide × 300mm deep trench around the entire building exterior, creating the final outer ring of the chemical barrier system. This completes the IS 6313 compliance.' },
    ]}
    faqs={[
      { q: "When should pre-construction termite treatment be done?", a: "IS 6313 specifies treatment at 5 stages: foundation trenches, backfill soil, plinth consolidation, wall-floor junctions, and external perimeter. Stages 1–4 must be completed before the respective concrete pours — making coordination with your contractor essential. We work directly with your construction team to schedule each stage." },
      { q: "Why is pre-construction treatment so much better than post-construction?", a: "During construction, soil is fully exposed, allowing a uniform, 100% continuous barrier. Post-construction treatment (Drill-Fill-Seal) can only achieve point-based coverage through drilled holes — leaving gaps in the barrier. IS 6313 pre-construction treatment is universally considered the gold standard by structural engineers and pest management professionals." },
      { q: "What is the warranty for pre-construction termite treatment?", a: "A to Z Pest Solutions provides a 10-year warranty on pre-construction treatment. If any termite activity is detected within the warranty period, we re-treat at no cost. The warranty is documented in an official certificate that can be registered with BBMP and included in property sale documents." },
      { q: "Is pre-construction treatment required by law in India?", a: "BIS IS 6313 (Part 2) is a mandatory standard for buildings under BBMP and other municipal corporations. Many housing finance companies (SBI, LIC Housing Finance, HDFC) require a pre-construction termite treatment certificate before approving home loans for properties in termite-prone areas." },
      { q: "Can pre-construction treatment be done on an ongoing construction site?", a: "Yes. Treatment can be phased to match construction milestones. Our team coordinates with your site engineer or contractor to complete each treatment stage at the appropriate construction phase. Missing a stage significantly reduces barrier effectiveness, so we strongly recommend engaging us before foundation work begins." },
      { q: "What chemicals are used and are they safe for the building structure?", a: "We use CIB-registered Chlorpyrifos 20% EC or Bifenthrin 10% EC termiticides. These are specifically formulated for soil application — they do not affect concrete strength, steel reinforcement, or any building materials. They biodegrade slowly in soil, maintaining efficacy for 10+ years." },
      { q: "What is the cost of pre-construction termite treatment?", a: "Treatment cost is calculated per square foot of built-up area. Typical costs range from ₹8 to ₹18 per sq ft depending on soil conditions and construction type. For a 1,500 sq ft house, treatment costs approximately ₹12,000–₹27,000 — a fraction of the cost of repairing termite structural damage later." },
      { q: "Can pre-construction treatment be done on a ground-floor flat in an apartment complex?", a: "Yes. For apartments, pre-construction treatment is typically organized by the builder for the entire complex. If your builder did not conduct treatment, we can still assess ground floor and basement units for post-construction treatment options." },
    ]}
  />
}
