import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/rodent.png'
import bgImage from '../../assets/services/bg/rodent.png'

export default function RodentTreatment() {
  return <ServiceDetailPage
    meta={{ title: 'Rodent Control in Bangalore | Rat & Mouse Treatment | A to Z Pest Solutions', desc: 'Professional rat and mouse control in Bangalore using tamper-resistant bait stations, snap traps & exclusion. Safe for family & pets. Call 9845559710 for FREE inspection.', canonical: 'https://pestcontrolbengaluru.in/rodent-treatment' }}
    image={imgPest} bgImage={bgImage} title="Rodent Treatment" tagline="A single pair of rats can produce 2,000 offspring per year. Our Integrated Rodent Management eliminates the problem at the root."
    intro="Rattus norvegicus (Norway rat) and Mus musculus (house mouse) are among the most economically destructive pests in urban India. In Bangalore, rising construction and rapid urbanization continuously displace rodent populations into residential and commercial spaces. Rodents contaminate 20% of the world's food supply annually, gnaw through electrical wiring (causing 25% of unexplained building fires in India), and transmit 35 documented diseases including Leptospirosis, Rat-Bite Fever, and Salmonellosis. A to Z Pest Solutions implements a structured 3-phase Integrated Rodent Management (IRM) program: Detection & Monitoring, Rodenticide Bait Station Deployment, and Exclusion & Proofing — providing complete, lasting rodent elimination."
    signs={['Fresh droppings (dark, 10–20mm) near food storage, along walls, or in cupboards','Gnaw marks on electrical cables, pipes, food packaging, or structural wood','Scratching, scurrying, or squeaking sounds in walls, ceilings, or attic at night','Grease rub marks (dark smears) along walls and baseboards from regular runways','Rodent nests made from shredded paper, insulation, or fabric in secluded areas','Burrows or entry holes (2.5cm+) along exterior walls, under doors, or near drains','Footprints or tail-drag marks visible in dusty or muddy areas','Unusual pet behavior — dogs or cats pawing at walls or sniffing at specific areas']}
    benefits={['Tamper-resistant, child and pet-safe bait stations placed on active runways','Professional-grade second-generation anticoagulant rodenticides (Bromadiolone)','Physical exclusion — sealing entry gaps with galvanized steel wool and wire mesh','Monitoring visits to track population decline and bait consumption','Complete removal of dead rodents to prevent secondary poisoning of pets','Detailed property survey report with all entry points mapped','Commercial rat control for warehouses, restaurants, hotels, and factories','Sanitation advisory to remove attractants and prevent re-entry']}
    process={[
      { title: 'Rodent Activity Survey & Species Identification', desc: 'A trained technician inspects the entire property — interior and exterior — identifying species (rat vs. mouse), active runways, burrows, gnaw damage, and all potential entry gaps. A survey report is provided with photographic documentation.' },
      { title: 'Tamper-Resistant Bait Station Deployment', desc: 'Lockable, tamper-resistant bait stations (safe from children and non-target animals) are strategically placed along confirmed runways, near burrow entrances, and at common entry points. Each station contains a professional rodenticide block (Bromadiolone 0.005%).' },
      { title: 'Snap Trap & Glue Board Placement', desc: 'For active indoor infestation, snap traps and heavy-duty glue boards are placed in areas where bait stations are unsuitable — inside food preparation areas, loft spaces, and server rooms.' },
      { title: 'Exclusion & Proofing', desc: 'All identified entry gaps are sealed using a combination of galvanized steel wool, wire mesh (19-gauge), and expanding foam sealant. Door sweeps and drain guards are installed where required, making re-entry physically impossible.' },
      { title: 'Monitoring & Progressive Removal', desc: 'We return every 3–5 days for the first 2 weeks to check stations, reset traps, and safely dispose of carcasses using PPE. Bait consumption is tracked to measure population decline. Service is complete when zero activity is recorded for 7 consecutive days.' },
    ]}
    faqs={[
      { q: "How do I know if I have rats or mice?", a: "Rat droppings are 10–20mm, banana-shaped, and tapered at one end. Mouse droppings are smaller (3–6mm) and rod-shaped. Rats gnaw large holes (2.5cm+) while mice create smaller holes (1cm). Rats are generally nocturnal while mice are active at dawn and dusk." },
      { q: "What diseases can rats and mice transmit in Bangalore?", a: "In Bangalore, documented rodent-borne diseases include Leptospirosis (spread through urine-contaminated water), Rat-Bite Fever, Salmonellosis (food contamination), and Murine Typhus. Rodents also carry fleas and ticks that can spread additional pathogens." },
      { q: "Are rodenticide bait stations safe for my children and pets?", a: "Yes. All bait stations we use are tamper-resistant, child-proof, and lockable — physical access by children or pets is impossible. The rodenticide inside (Bromadiolone 0.005%) is formulated at concentrations specifically lethal to rodents at the quantities they consume, but non-toxic at pet-contact exposures." },
      { q: "How long does complete rodent elimination take?", a: "Most residential infestations are resolved in 2–3 weeks. Severe infestations or large commercial properties may take 4–6 weeks. Our monitoring visits continue until zero activity is confirmed for 7 consecutive days." },
      { q: "Why should I use a professional instead of buying traps from a store?", a: "Store-bought snap traps catch individual rodents but do not address the entry points that allow unlimited new rodents to enter, or the colony outside your home. Our IRM program eliminates the entire local population AND seals all entry points — providing a permanent solution." },
      { q: "Can rats chew through walls and concrete?", a: "Norway rats can chew through soft concrete, wood, brick, and aluminum. They cannot chew through galvanized steel or tempered glass. This is why our exclusion service uses 19-gauge galvanized wire mesh — the only truly rat-proof sealing material." },
      { q: "What is the cost of rodent control in Bangalore?", a: "Residential rodent control costs ₹2,000–₹5,000 for a standard apartment. Commercial premises, warehouses, and restaurants are priced based on area (typically ₹8,000–₹35,000). Monthly maintenance contracts are available starting at ₹1,500/month." },
      { q: "Do ultrasonic pest repellers work against rats?", a: "Scientific studies, including those by the Journal of Pest Science, have found ultrasonic devices to be largely ineffective against rodents. Rats habituate to the sound within days. Professional bait stations and exclusion are the only evidence-based solutions." },
      { q: "What can I do to prevent rats from entering my home?", a: "Seal all gaps above 6mm at ground level, install door sweeps on all external doors, keep garbage bins sealed and away from the building, store food in hard plastic or glass containers, and trim vegetation that touches the building. Our technicians provide a detailed prevention checklist." },
      { q: "Are dead rats dangerous after treatment?", a: "Yes. Dead rodents can harbor fleas and other parasites that transfer to pets and humans. They also decompose rapidly in warm weather, creating serious odor and hygiene issues. Our team removes all dead rodents using PPE and disposes of them hygienically during each monitoring visit." },
    ]}
  />
}
