// SSR-safe Image Assets Data Store

const defaultImages = [
  {
    id: 'img-logo',
    name: 'Logo Emblem',
    path: '/images/logo.webp',
    pageLocation: 'Global Header, Mobile Navbar & Footer',
    componentContext: 'Brand Header & Navbar',
    alt: 'A to Z Pest Solutions Bangalore Logo Emblem',
    title: 'A to Z Pest Solutions Logo',
    storageType: 'Local Project File',
    storagePath: 'public/images/logo.webp',
    dimensions: '512 x 512 px',
    fileSize: '45 KB',
    category: 'Branding',
  },
  {
    id: 'img-hero-banner',
    name: 'Homepage Hero Banner',
    path: '/images/hero-banner.webp',
    pageLocation: 'Home Page -> Main Hero Section',
    componentContext: 'HeroSection.jsx',
    alt: 'Professional pest control team conducting inspection in Bangalore home',
    title: 'Pest Control Bangalore Hero Banner',
    storageType: 'Local Project File',
    storagePath: 'public/images/hero-banner.webp',
    dimensions: '1920 x 1080 px',
    fileSize: '185 KB',
    category: 'Home Page',
  },
  {
    id: 'img-termite',
    name: 'Termite Control Image',
    path: '/images/pests/termite.webp',
    pageLocation: 'Termite Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Termite Page',
    alt: 'Subterranean termite control drill-fill-seal barrier treatment in Bangalore',
    title: 'Termite Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/termite.webp',
    dimensions: '800 x 600 px',
    fileSize: '936 KB',
    category: 'Services',
  },
  {
    id: 'img-bedbug',
    name: 'Bed Bug Treatment Image',
    path: '/images/pests/bed_bug.webp',
    pageLocation: 'Bed Bugs Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Bed Bug Page',
    alt: 'Odorless bed bug elimination and chemical treatment for mattress',
    title: 'Bed Bug Eradication Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/bed_bug.webp',
    dimensions: '800 x 600 px',
    fileSize: '762 KB',
    category: 'Services',
  },
  {
    id: 'img-cockroach',
    name: 'Cockroach Eradication Image',
    path: '/images/pests/cockroach.webp',
    pageLocation: 'Cockroach Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Cockroach Page',
    alt: 'Odorless Fipronil gel baiting application for kitchen cockroach control',
    title: 'Cockroach Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/cockroach.webp',
    dimensions: '800 x 600 px',
    fileSize: '730 KB',
    category: 'Services',
  },
  {
    id: 'img-rodent',
    name: 'Rodent Management Image',
    path: '/images/pests/rodent.webp',
    pageLocation: 'Rodent Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Rodent Page',
    alt: 'Integrated rodent exclusion gap sealing and tamper-proof bait stations',
    title: 'Rat & Rodent Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/rodent.webp',
    dimensions: '800 x 600 px',
    fileSize: '853 KB',
    category: 'Services',
  },
  {
    id: 'img-mosquito',
    name: 'Mosquito Control Image',
    path: '/images/pests/mosquito.webp',
    pageLocation: 'Mosquito Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Mosquito Page',
    alt: 'Bti larvicidal outdoor fogging and indoor mosquito vector management',
    title: 'Mosquito Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/mosquito.webp',
    dimensions: '800 x 600 px',
    fileSize: '723 KB',
    category: 'Services',
  },
  {
    id: 'img-honeybee',
    name: 'Honey Bee Relocation Image',
    path: '/images/pests/honey_bee.webp',
    pageLocation: 'Honey Bee Relocation Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Honey Bee Page',
    alt: 'Ethical beekeeper honey bee hive removal and safe relocation service',
    title: 'Honey Bee Safe Relocation',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/honey_bee.webp',
    dimensions: '800 x 600 px',
    fileSize: '725 KB',
    category: 'Services',
  },
  {
    id: 'img-woodborer',
    name: 'Wood Borer Preservation Image',
    path: '/images/pests/wood_borer.webp',
    pageLocation: 'Wood Borer Treatment Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Wood Borer Page',
    alt: 'Syringe injection into wood borer flight holes for furniture preservation',
    title: 'Wood Borer Treatment Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/wood_borer.webp',
    dimensions: '800 x 600 px',
    fileSize: '739 KB',
    category: 'Services',
  },
  {
    id: 'img-ant',
    name: 'Ant Control Image',
    path: '/images/pests/ant.webp',
    pageLocation: 'Ant Control Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Ant Page',
    alt: 'Targeted sugar and protein ant gel baiting for colony eradication',
    title: 'Ant Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/ant.webp',
    dimensions: '800 x 600 px',
    fileSize: '819 KB',
    category: 'Services',
  },
  {
    id: 'img-tick',
    name: 'Tick Control Image',
    path: '/images/pests/tick.webp',
    pageLocation: 'Tick Control Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Tick Page',
    alt: 'Pet-safe tick lifecycle disruption treatment for dog bedding & lawn',
    title: 'Tick Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/tick.webp',
    dimensions: '800 x 600 px',
    fileSize: '693 KB',
    category: 'Services',
  },
  {
    id: 'img-flea',
    name: 'Flea Control Image',
    path: '/images/pests/flea.webp',
    pageLocation: 'Flea Control Page & Services Grid',
    componentContext: 'ServicesGrid.jsx / Flea Page',
    alt: 'Insect growth regulator IGR spray for flea egg & larva elimination',
    title: 'Flea Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/flea.webp',
    dimensions: '800 x 600 px',
    fileSize: '715 KB',
    category: 'Services',
  },
  {
    id: 'img-residential',
    name: 'Residential Package Cover',
    path: '/images/pests/residential.webp',
    pageLocation: 'Residential Pest Control Page',
    componentContext: 'ResidentialCommercial.jsx',
    alt: 'Whole-house eco-friendly pest protection package in Bangalore',
    title: 'Residential Pest Control Package',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/residential.webp',
    dimensions: '800 x 600 px',
    fileSize: '795 KB',
    category: 'Packages',
  },
  {
    id: 'img-commercial',
    name: 'Commercial Facility Cover',
    path: '/images/pests/commercial.webp',
    pageLocation: 'Commercial Pest Control Page',
    componentContext: 'ResidentialCommercial.jsx',
    alt: 'Commercial warehouse and restaurant audit-compliant pest management',
    title: 'Commercial Pest Control Service',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/commercial.webp',
    dimensions: '800 x 600 px',
    fileSize: '828 KB',
    category: 'Packages',
  },
  {
    id: 'img-preconstruction',
    name: 'Pre-Construction Termite Barrier',
    path: '/images/pests/pre_construction.webp',
    pageLocation: 'Pre-Construction Termite Treatment Page',
    componentContext: 'Services.jsx',
    alt: 'Anti-termite chemical soil treatment for building foundation site',
    title: 'Pre-Construction Termite Treatment',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/pre_construction.webp',
    dimensions: '800 x 600 px',
    fileSize: '1.2 MB',
    category: 'Termite',
  },
  {
    id: 'img-postconstruction',
    name: 'Post-Construction Termite Eradication',
    path: '/images/pests/post_construction.webp',
    pageLocation: 'Post-Construction Termite Treatment Page',
    componentContext: 'Services.jsx',
    alt: 'Wall and floor drilling for termiticide chemical barrier injection',
    title: 'Post-Construction Termite Treatment',
    storageType: 'Local Project File',
    storagePath: 'public/images/pests/post_construction.webp',
    dimensions: '800 x 600 px',
    fileSize: '936 KB',
    category: 'Termite',
  },
  {
    id: 'img-blog-termite',
    name: 'Termite Guide Cover',
    path: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?auto=format&fit=crop&w=800&q=80',
    pageLocation: 'Blogs Page -> Termite Prevention Guide',
    componentContext: 'BlogPostPage.jsx',
    alt: 'Close-up of wooden structural termite damage inspection in Bangalore',
    title: 'Termite Inspection & Prevention',
    storageType: 'Unsplash CDN (Linked)',
    storagePath: 'External URL (Saved in Blog Engine)',
    dimensions: '800 x 533 px',
    fileSize: 'CDN Cloud',
    category: 'Blogs',
  },
  {
    id: 'img-blog-cockroach',
    name: 'Monsoon Pest Guide Cover',
    path: 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&w=800&q=80',
    pageLocation: 'Blogs Page -> Monsoon Cockroach Guide',
    componentContext: 'BlogPostPage.jsx',
    alt: 'Sanitized modern kitchen counter protected against cockroach infestation',
    title: 'Monsoon Kitchen Pest Prevention',
    storageType: 'Unsplash CDN (Linked)',
    storagePath: 'External URL (Saved in Blog Engine)',
    dimensions: '800 x 533 px',
    fileSize: 'CDN Cloud',
    category: 'Blogs',
  }
]

const KEY = 'atoz_admin_image_assets'

export function getImages() {
  if (typeof window === 'undefined') return defaultImages
  try {
    const raw = localStorage.getItem(KEY)
    if (!raw) {
      localStorage.setItem(KEY, JSON.stringify(defaultImages))
      return defaultImages
    }
    return JSON.parse(raw)
  } catch (e) {
    return defaultImages
  }
}

export function updateImage(id, updatedFields) {
  if (typeof window === 'undefined') return
  const current = getImages()
  const updated = current.map(item => item.id === id ? { ...item, ...updatedFields } : item)
  try {
    localStorage.setItem(KEY, JSON.stringify(updated))
  } catch (e) {
    console.error('Failed to update image asset', e)
  }
  return updated
}
