import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/ant.png'
import bgImage from '../../assets/services/bg/cockroach.png'

export default function AntPestControl() {
  return <ServiceDetailPage
    meta={{ title: 'Ant Pest Control in Bangalore | A to Z Pest Solutions', desc: 'Professional ant control in Bangalore. Colony-eliminating gel bait targets the queen for permanent results. Safe for kitchen & family. Call 9845559710 for FREE inspection.' }}
    image={imgPest} bgImage={bgImage} title="Ant Pest Control" tagline="Killing the ants you see accomplishes nothing — you must eliminate the queen. Our colony-targeting bait system does exactly that."
    intro="Ants are highly organized superorganisms — a single Argentine ant (Linepithema humile) supercolony in Bangalore can contain millions of workers across thousands of sub-nests. Common ant species in Bangalore include the Black Garden Ant (Lasius niger), Pharaoh Ant (Monomorium pharaonis), Carpenter Ant (Camponotus compressus), Fire Ant (Solenopsis invicta), and the Weaver Ant (Oecophylla smaragdina). Simply spraying visible worker ants is counterproductive — the colony detects the chemical threat and undergoes 'budding' (splitting into multiple sub-colonies), rapidly worsening the infestation. A to Z Pest Solutions uses professional slow-acting gel bait systems (Fipronil or Indoxacarb-based) that worker ants carry back to the colony and share with nest mates through trophallaxis (food sharing), achieving total colony elimination including the egg-laying queen within 3–7 days."
    signs={['Persistent ant trails along walls, countertops, window sills, and electrical conduits','Winged ants (reproductives/alates) appearing near windows or light sources — indicates a mature colony nearby','Small mounds of sandy or granular soil near walls, under flooring, or in garden areas','Ants congregating around food spills, pet food, unsealed sugar, or fruit','Hollowed-out or structurally damaged wood with sawdust-like frass (Carpenter Ants)','Ants found in electrical junction boxes, switchboards, or appliances (causes short circuits)','Small pinholes in walls with debris excavated around them (indicates nesting inside wall cavities)','Stings or bites on family members or pets — Fire ants cause a distinctive burning sensation']}
    benefits={['Slow-acting Fipronil/Indoxacarb gel bait achieves total colony elimination including the queen','Trophallaxis transfer mechanism spreads the bait throughout the entire colony network','No need to locate or expose the nest — bait is carried to it by worker ants','Food-safe gel bait formulation — placed precisely in crevices, inaccessible to children and pets','Barrier treatment with Bifenthrin 10% EC around exterior perimeter prevents new colonies from entering','Species identification included — different ant species require different bait attractants (protein vs. carbohydrate)','Treatment effective against all 5 major ant species found in Bangalore residences and offices','Rapid visible reduction in ant activity within 24–48 hours']}
    process={[
      { title: 'Species Identification & Colony Mapping', desc: 'Identification of the specific ant species is critical — Pharaoh Ants require carbohydrate-based bait, while Carpenter Ants and Fire Ants respond best to protein-based bait. Our technician observes worker ant behavior, trail patterns, and physical characteristics to identify the species and trace trails back to the primary and satellite nests.' },
      { title: 'Strategic Gel Bait Deployment', desc: 'Professional-grade gel bait (Fipronil 0.01% or Indoxacarb 0.6%) is placed in precise 0.1g droplets at 20cm intervals along all active trails, near entry points, and at suspected nest locations. The slow-acting formulation takes 24–72 hours to kill — sufficient time for workers to distribute it throughout the colony through food sharing (trophallaxis).' },
      { title: 'Colony Cascade Elimination', desc: 'As worker ants feed on the bait and return to the nest, they regurgitate it to larvae, other workers, and the queen. The colony-level mortality cascade typically achieves 90%+ population reduction in 3–5 days and complete elimination within 7–10 days — including all satellite nests in the building.' },
      { title: 'Exterior Perimeter Barrier Treatment', desc: 'Bifenthrin 10% EC residual spray is applied around the building exterior — foundation perimeter, window frames, door thresholds, and drain entry points — creating a chemical barrier that prevents new ant colonies from entering the structure for 60–90 days.' },
      { title: 'Monitoring & Sanitation Advisory', desc: 'We return at 14 days to assess colony elimination and re-apply bait if any activity persists. We also provide a detailed sanitation checklist: sealing food in airtight containers, fixing moisture issues (ants are strongly attracted to water), caulking wall cracks, and managing garden vegetation that touches the building.' },
    ]}
    faqs={[
      { q: "Why do more ants appear after I spray them?", a: "Common sprays kill only the workers they directly contact. The colony detects the chemical threat and triggers 'budding' — dividing the colony into multiple sub-nests, each with a new queen. This response rapidly expands the infestation. Our slow-acting bait is specifically designed to be undetected by the colony until it is too late for budding to occur." },
      { q: "How long does ant bait take to work?", a: "You will see a significant reduction in visible ant activity within 24–48 hours. Complete colony collapse typically occurs within 5–10 days as the bait cascades through the colony hierarchy." },
      { q: "Are ant baits safe for my kitchen and pets?", a: "Yes. Fipronil gel at 0.01% concentration is formulated at levels that are specifically lethal to insects at the micro-doses ants consume, but safe for mammals. Bait is placed in crevices inaccessible to children and pets. Bifenthrin perimeter spray is applied only on exterior surfaces." },
      { q: "Can ants damage my home structure?", a: "Carpenter Ants (Camponotus compressus) excavate wood to build nests, causing structural damage similar to termites — particularly in moisture-damaged timber (window frames, roof beams near leaks). Unlike termites, they do not eat wood, but the galleries they create can significantly weaken structural elements over time." },
      { q: "What is the cost of ant pest control in Bangalore?", a: "Standard ant treatment for a 2BHK apartment costs ₹1,500–₃,000. Properties with Carpenter Ant infestations requiring wood treatment cost ₹3,000–₹6,000. Commercial premises and restaurants with large-scale ant problems are quoted separately." },
      { q: "Why do I have so many ants suddenly?", a: "A sudden surge in visible ant activity typically indicates a newly established nearby colony that has found a foraging trail to your property, or that a previous colony has undergone budding. Seasonal triggers include monsoon rains (which flood ground nests, driving ants indoors) and hot, dry weather (ants seek moisture)." },
      { q: "Can ants contaminate food and cause illness?", a: "Yes. Pharaoh Ants (small, yellowish) are particularly dangerous in hospital and kitchen environments — they have been documented spreading Salmonella, Staphylococcus, Clostridium, and Streptococcus. They are attracted to wounds in hospital settings. Regular professional pest control is mandatory for FSSAI-licensed kitchens." },
      { q: "How can I prevent ants from coming back?", a: "Seal all cracks in walls and flooring with silicone caulk, store all food in airtight containers, fix leaking faucets, keep kitchen drains clean, and trim vegetation touching the building. Our quarterly maintenance plan provides ongoing perimeter treatments that prevent new colony establishment." },
    ]}
  />
}
