import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/mosquito.png'
import bgImage from '../../assets/services/bg/mosquito.png'

export default function MosquitoTreatment() {
  return <ServiceDetailPage
    meta={{ title: 'Mosquito Control in Bangalore | A to Z Pest Solutions', desc: 'Professional mosquito treatment in Bangalore. ULV fogging, larvicidal & residual spray to eliminate Dengue, Malaria & Chikungunya risks. Call 9845559710 for FREE inspection.' }}
    image={imgPest} bgImage={bgImage} title="Mosquito Treatment" tagline="Bangalore reports 8,000+ Dengue cases annually. Our 3-stage mosquito control protects your family all season long."
    intro="Bangalore's tropical climate — with temperatures between 15–35°C year-round and two monsoon seasons — creates ideal breeding conditions for Aedes aegypti (Dengue vector), Anopheles stephensi (Malaria vector), and Culex quinquefasciatus (Filariasis vector). According to BBMP health reports, dengue cases in Bangalore have increased by 60% over the past five years, with peak transmission during July–October and January–February. A to Z Pest Solutions employs a WHO-recommended Integrated Vector Management (IVM) approach: Bti larvicidal treatment destroys mosquito breeding at the source, ULV cold fogging eliminates adult populations in outdoor areas, and indoor residual spray provides 60-day protection inside your home."
    signs={['Persistent mosquito bites indoors — even with windows closed — indicates indoor breeding','Visible mosquito larvae (tiny, comma-shaped, wriggling) in still water containers','Buzzing sounds near ears at night or hearing them in dark rooms','Standing water accumulating in flower pots, AC drip trays, bird baths, or clogged gutters','Sudden increase in mosquito activity in your neighborhood, garden, or terrace','Dengue or chikungunya cases reported among neighbors or in your housing society','Stagnant water visible in terrace water tanks, drain pipes, or construction areas','Ankle and foot bites indoors during daytime — hallmark of Aedes aegypti (dengue mosquito)']}
    benefits={['ULV cold fogging kills 98%+ of adult mosquitoes in treated outdoor areas within minutes','Bacillus thuringiensis israelensis (Bti) larvicide — a biological agent safe for humans, fish, and animals — destroys larvae before they hatch','WHO Pesticide Evaluation Scheme (WHOPES) approved formulations only','Indoor residual spray on walls and curtains provides 45–60 days protection','Covers apartments, villas, gardens, offices, schools, hotels, and event venues','No need to evacuate — residents can return to treated areas within 30–60 minutes','Quarterly AMC (Annual Maintenance Contract) plans available for year-round protection','Pre-monsoon and post-monsoon treatment packages for peak season coverage']}
    process={[
      { title: 'Breeding Site Survey & Mapping', desc: 'A technician conducts a systematic survey of the property, identifying all potential and active breeding sites — flower pot saucers, AC condensate trays, terrace water accumulation, construction material puddles, rooftop water tanks, and drainage areas. A Breteau Index (BI) assessment is performed to quantify infestation density.' },
      { title: 'Larvicidal Treatment (Source Elimination)', desc: 'Bacillus thuringiensis israelensis (Bti) biological larvicide is applied to all identified water bodies that cannot be drained or covered. This 100% biological agent kills mosquito larvae within 24 hours with zero toxicity to humans, pets, fish, or beneficial insects.' },
      { title: 'ULV Cold Fogging (Adult Population Control)', desc: 'Ultra-Low Volume (ULV) fogging machines disperse 3–20 micron droplets of WHO-approved insecticide (Malathion 5% or Deltamethrin 0.5%) through gardens, exterior spaces, bushes, trees, and building exteriors — killing adult mosquitoes on contact.' },
      { title: 'Indoor Residual Spray', desc: 'Cypermethrin 10% WP is applied to interior walls (especially corners, behind curtains, and dark resting areas) creating a residual surface treatment. Mosquitoes resting on treated surfaces absorb a lethal dose within minutes — effective for 45–60 days.' },
      { title: 'Source Reduction Guidance & Follow-Up', desc: 'Our technician provides a detailed source reduction checklist — proper coverage of water storage tanks, weekly draining of plant saucers, drainage management, and construction water management. A follow-up inspection is conducted 21 days post-treatment to assess efficacy and retreat if needed.' },
    ]}
    faqs={[
      { q: "Which mosquitoes cause Dengue in Bangalore?", a: "Dengue in Bangalore is caused by Aedes aegypti mosquitoes, which breed in small, clean water containers and bite primarily during the day (2 hours after sunrise and 2 hours before sunset). They are identifiable by distinctive black-and-white striped legs." },
      { q: "When is mosquito season in Bangalore?", a: "Bangalore has two peak mosquito seasons: July–October (Southwest Monsoon) and January–February (Northeast Monsoon post-season). However, Bangalore's mild climate means mosquitoes are present year-round. We recommend quarterly treatments for year-round protection." },
      { q: "Is ULV fogging safe for children and pets?", a: "Yes, when conducted correctly. We request that residents stay indoors during fogging and for 30 minutes after treatment. Pets should be kept inside with windows closed during this period. The fine droplets disperse rapidly and the WHO-approved insecticides used are safe once the initial mist settles." },
      { q: "How long does the mosquito treatment last?", a: "Larvicidal treatment prevents new mosquitoes emerging from breeding sites for 2–4 weeks (requires repeat application if water bodies are refilled). ULV fogging eliminates adults within 24 hours. Indoor residual spray protects for 45–60 days. We recommend monthly or quarterly treatments during peak season." },
      { q: "What is the Breteau Index and why does it matter?", a: "The Breteau Index (BI) is an epidemiological tool measuring the number of positive mosquito-breeding containers per 100 inspected households. A BI above 5 indicates dengue transmission risk. Our pre-treatment survey calculates your property's BI to determine treatment intensity." },
      { q: "Can mosquitoes breed inside my apartment?", a: "Yes. Common indoor breeding sites include AC condensate drip trays (a leading Dengue breeding site in Bangalore), bathroom drain stoppers with standing water, flower vases, and underused storage containers. Our indoor survey identifies and eliminates all interior breeding sites." },
      { q: "What is the cost of mosquito treatment in Bangalore?", a: "Mosquito treatment for a standard 2BHK apartment costs ₹1,500–₹2,500. Villa and bungalow treatments range from ₹3,000–₹6,000. Housing society and commercial property pricing is based on square footage. Annual Maintenance Contracts start at ₹4,500/year." },
      { q: "Is fogging alone enough to control mosquitoes?", a: "No. Fogging kills only adult mosquitoes present at the time of treatment. Without larvicidal treatment and source reduction, a new adult population emerges from untreated breeding sites within 7–10 days. A complete IVM (Integrated Vector Management) approach — breeding control + adult control — is essential for lasting results." },
      { q: "Why are mosquitoes more active at certain times?", a: "Aedes aegypti (Dengue) is a daytime biter, most active 2 hours after sunrise and before sunset. Culex (Filariasis/encephalitis) mosquitoes are peak active between 9 PM and midnight. Anopheles (Malaria) bite predominantly between midnight and dawn. Treatment strategies vary based on species." },
      { q: "Can I do mosquito control myself?", a: "DIY methods like coils, mats, and repellents only provide personal protection — they do not reduce the mosquito population. Eliminating breeding sites yourself (emptying stagnant water) is helpful but insufficient for established infestations. Professional ULV fogging and larvicidal treatment are required for significant population reduction." },
    ]}
  />
}
