import ServiceDetailPage from './ServiceDetailPage'
import imgPest from '../../assets/services/wood_borer.png'
import bgImage from '../../assets/services/bg/wood_borer.png'

export default function WoodBorerTreatment() {
  return <ServiceDetailPage
    meta={{ title: 'Wood Borer Treatment in Bangalore | A to Z Pest Solutions', desc: 'Expert wood borer beetle treatment in Bangalore. Injection into flight holes, surface spray & fumigation for furniture and structural timber. Call 9845559710 for FREE inspection.' }}
    image={imgPest} bgImage={bgImage} title="Wood Borer Treatment" tagline="Wood borers destroy furniture from the inside out — invisible until the damage is catastrophic. Protect your wooden assets today."
    intro="Wood-boring beetles — primarily the Powder Post Beetle (Lyctus brunneus), Common Furniture Beetle (Anobium punctatum), and Longhorn Beetle (Cerambycidae family) — lay eggs inside timber, and their larvae tunnel through the wood for 1–3 years before emerging as adults. By the time the characteristic 'exit holes' are visible, the internal structure of the wood is often already 70–80% destroyed. In Bangalore's humid climate, wood borer infestations in furniture, flooring, roof timber, and window frames are extremely common, especially in teak, pine, and plywood. A to Z Pest Solutions provides a clinically precise treatment combining insecticide injection directly into flight holes, borate-based surface treatment, and where necessary, phosphine gas fumigation for museum-quality or highly valuable pieces."
    signs={['Small, round or oval exit holes (1–8mm diameter) appearing on furniture surfaces','Fine, talcum-powder-like frass (bore dust) falling from holes or collecting beneath furniture','Live adult beetles (2–8mm, dark brown) found on or near wooden furniture, especially in spring and summer','Weakened, hollow-sounding wood when tapped — indicating extensive internal tunnel networks','Crumbling or damaged edges on timber, floors, or roof beams','Gallery tunnels visible in cross-sections of broken or dissected wood','Squeaking floorboards that were previously silent (indicates weakened internal structure)','Fine dust or holes appearing inside wooden wardrobes, shelves, or drawers']}
    benefits={['Precision injection of Bifenthrin or Permethrin insecticide directly into each exit hole — reaching larvae deep in the wood','Borate (Disodium Octaborate Tetrahydrate) surface treatment — penetrates wood grain and provides 3–5 year residual protection','Fumigation with Phosphine gas for highly infested pieces — 100% mortality at all life stages','Safe for polished, varnished, and painted wood surfaces — no staining or finish damage','No disassembly of furniture required in most cases','Effective against all species: Powder Post Beetles, Furniture Beetles, and Longhorn Beetles','Treatment certificate issued for insurance, property valuation, and sale purposes','Quarterly monitoring visits available to detect re-infestation early']}
    process={[
      { title: 'Wood Damage Assessment & Species Identification', desc: 'Our specialist inspects all wooden furniture, flooring, structural beams, and roof timber. Exit hole diameter, frass texture, and damage pattern are used to identify the specific beetle species — which determines the most effective treatment chemical and method.' },
      { title: 'Flight Hole Injection Treatment', desc: 'A blunt-tip injection needle is inserted into each visible exit hole. Bifenthrin 10% EC or Permethrin 25% EC insecticide is pressure-injected directly into the tunnel network — reaching and killing larvae at depths of 5–10cm that surface sprays cannot penetrate.' },
      { title: 'Borate Surface Treatment', desc: 'Disodium Octaborate Tetrahydrate (DOT) solution is applied to all exposed wood surfaces using brush or spray. Borates penetrate the wood grain and create a toxic zone that kills any larvae attempting to feed on treated wood. Borates are safe for humans and pets once dry.' },
      { title: 'Fumigation (For Severe Cases)', desc: 'Highly infested or artistically valuable pieces are fumigated using Phosphine (Aluminium Phosphide) gas in a sealed fumigation chamber. This achieves 100% mortality across all life stages (egg, larva, pupa, and adult) and is the gold standard for museum-grade conservation treatment.' },
      { title: 'Sealing, Polishing Guidance & Follow-Up', desc: 'After treatment, exit holes are sealed with wood-colored filler. We provide detailed guidance on applying wax or polish to treated surfaces. A follow-up inspection at 60 days confirms that no new exit holes have appeared (which would indicate missed larvae). New holes after treatment trigger free re-treatment.' },
    ]}
    faqs={[
      { q: "Which types of wood are most vulnerable to wood borers in Bangalore?", a: "Sapwood of all species is vulnerable, but softwoods and hardwoods with high starch content are most at risk. In Bangalore, commonly infested wood includes plywood (inner veneers), pine, sapele, and lower-grade teak. Aged, seasoned hardwood teak is naturally more resistant but not immune." },
      { q: "What is the difference between termites and wood borers?", a: "Termites (social insects) attack wood from the outside in, building mud tubes and consuming cellulose. Wood borers (beetle larvae) attack from the inside out — eggs are laid in cracks and larvae tunnel through wood for years. Termite damage is often structural; wood borer damage appears as exit holes and bore dust. Both require different treatments." },
      { q: "How long does wood borer treatment take?", a: "Treatment of a 3-bedroom home's furniture typically takes 3–5 hours. The flight hole injection process is methodical — each hole must be individually treated. Borate surface treatment adds another 1–2 hours. Fumigation, if required, takes 48–72 hours." },
      { q: "Can I still use my furniture after treatment?", a: "Yes. After injection treatment, the insecticide inside the holes is not accessible to surface contact. Borate-treated surfaces are safe once dry (approximately 4 hours). Fumigated items require 24-hour airing before use. We provide specific instructions for each treated piece." },
      { q: "Will the treatment affect the finish or polish of my furniture?", a: "No. We use water-based Borate solution that does not damage lacquer, varnish, wax, or paint finishes. Bifenthrin injection is confined inside the holes. The treatment process is specifically designed to preserve the cosmetic appearance of all furniture." },
      { q: "How do I know if my wood borer infestation is active or old?", a: "Active infestations produce fresh frass — fine, cream-colored powder that feels like talcum powder. Old exit holes contain no fresh frass — the dust inside is compacted and grey. If you blow into a hole and see fresh powder fall out, the infestation is active and requires immediate treatment." },
      { q: "What is the cost of wood borer treatment in Bangalore?", a: "Treatment costs range from ₹2,500 for 5–8 pieces of furniture to ₹12,000 for a fully infested home with structural timber. Pricing depends on the number of pieces, species of wood borer, and treatment method (injection vs. fumigation)." },
      { q: "Can wood borers spread from one piece of furniture to another?", a: "Yes. Adult wood borer beetles that emerge from infested furniture can fly and lay eggs in nearby wood — spreading the infestation to other furniture in the same room. This is why treating only one piece is insufficient; all wooden furniture should be inspected and treated as part of a comprehensive program." },
      { q: "What follow-up support do you provide?", a: "We provide free re-treatment visits for injection treatment if new exit holes appear after treatment. Borate surface treatment includes ongoing protection against new infestation." },
      { q: "Can wood borers cause structural damage to my home?", a: "Yes. If structural roof beams, floor joists, or load-bearing timber are infested, wood borers can compromise structural integrity over several years. We strongly recommend annual inspection of all roof timber, particularly in older Bangalore properties built before 1990 using solid wood construction." },
    ]}
  />
}
